### ISSUE TITLE
Create definitions for game entities

### ISSUE THREAD

**Issue by Sorgas** [Sorgas/Tearfall#3]
Items, buildings, crafting recipes, creatures and plants are defined in core/assets/resources.

**Comment by GlennHoran** [comment]
Just checking, do you just want people to add more game entity objects to plans/creatures etc?

**Comment by Sorgas** [comment]
> Just checking, do you just want people to add more game entity objects to plans/creatures etc?

Yes, I found it fine for someone unfamiliar with project. However, any other contribution is appreciated as well.
